"""add meeting update fields

Revision ID: 8d93fd3f7e0a
Revises: 390278028672
Create Date: 2026-03-18 18:37:40.755576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d93fd3f7e0a'
down_revision = '390278028672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_note', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_updated_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('last_updated_by')
        batch_op.drop_column('update_note')

    # ### end Alembic commands ###
