"""update resource fields

Revision ID: 8fbb7b6f1d81
Revises: 8d93fd3f7e0a
Create Date: 2026-04-08 10:31:04.244378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbb7b6f1d81'
down_revision = '8d93fd3f7e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('branch', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('section', sa.String(length=20), nullable=False))
        batch_op.drop_column('course')
        batch_op.drop_column('semester')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('section')
        batch_op.drop_column('branch')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
